<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DLSS_Swapper.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>$(DefineConstants);LINUX_CORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AsyncAwaitBestPractices" Version="10.0.0" />
    <PackageReference Include="AsyncAwaitBestPractices.MVVM" Version="10.0.0" />
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="FuzzySharp" Version="2.0.2" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />
    <PackageReference Include="sqlite-net-e" Version="1.11.0" />
    <PackageReference Include="ValveKeyValue" Version="0.70.0.499" />
    <PackageReference Include="YamlDotNet" Version="18.1.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="../Data/GameHistory.cs" Link="Data/GameHistory.cs" />
    <Compile Include="../Data/GameAssetType.cs" Link="Data/GameAssetType.cs" />
    <Compile Include="../Data/NVIDIA/ListBucketResult.cs" Link="Data/NVIDIA/ListBucketResult.cs" />
    <Compile Include="../Data/NVIDIA/ListBucketResultContents.cs" Link="Data/NVIDIA/ListBucketResultContents.cs" />
    <Compile Include="../Helpers/ResourceHelper.cs" Link="Helpers/ResourceHelper.cs" />
    <Compile Include="../Logger.cs" Link="Logger.cs" />
    <Compile Include="../Storage.cs" Link="Storage.cs" />
    <EmbeddedResource Include="../Assets/static_manifest.json" Link="Assets/static_manifest.json" />
    <EmbeddedResource Include="../Acknowledgements/**/notes.md" Link="Acknowledgements/%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="../Acknowledgements/**/license.txt" Link="Acknowledgements/%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="../Translations/**/*.resw" Link="Translations/%(RecursiveDir)%(Filename)%(Extension)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
